DROP ALL OBJECTS;
CREATE TABLE IF NOT EXISTS films
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         varchar NOT NULL,
    description  varchar,
    release_date date,
    duration     integer,
    MPA_ID       BIGINT
);

CREATE TABLE IF NOT EXISTS users
(
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    varchar NOT NULL,
    login    varchar NOT NULL,
    name     varchar,
    birthday date
);

CREATE TABLE IF NOT EXISTS likes
(
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER REFERENCES users (id),
    film_id INTEGER REFERENCES films (id)
);

CREATE TABLE IF NOT EXISTS friends
(
    user_id     INTEGER REFERENCES USERS (id),
    friend_id   INTEGER REFERENCES USERS (id),
    are_friends boolean
);

CREATE TABLE IF NOT EXISTS genres
(
    id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title varchar
);

CREATE TABLE IF NOT EXISTS films_genres
(
    film_id  INTEGER REFERENCES FILMS (id),
    genre_id INTEGER REFERENCES GENRES (id)
);

CREATE TABLE IF NOT EXISTS MPA
(
    id BIGINT NOT NULL AUTO_INCREMENT,
    name CHARACTER VARYING NOT NULL,
    CONSTRAINT MPA_PK PRIMARY KEY (id)
);